name: Test

on: [push]

jobs:
  test:
    name: Unit Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake -Dunittests=ON ..
    - name: build
      run: |
        cd build
        cmake --build . --config Release -j 8
    - name: test
      run: |
        cd build
        ctest . -j 8 -C Release -V
